import {FFmpeg} from '@ffmpeg/ffmpeg';
import {ass,validCuts,total} from './model';
let engine=null,loading=null,logs=[],listeners={};
export function cancelMedia(){engine?.terminate();engine=null;loading=null;}
export async function ff(status){if(engine?.loaded)return engine;if(loading)return loading;loading=(async()=>{status('영상 처리 엔진을 불러오는 중… 첫 실행 약 32MB');const f=new FFmpeg();engine=f;f.on('log',e=>{logs.push(e.message);if(logs.length>200)logs.shift()});f.on('progress',e=>listeners.progress?.(e.progress));await f.load({coreURL:new URL('/core/ffmpeg-core.js',location.origin).href,wasmURL:new URL('/core/ffmpeg-core.wasm',location.origin).href});await f.createDir('fonts');await f.writeFile('fonts/font.ttf',new Uint8Array(await(await fetch('/fonts/NanumMyeongjo-ExtraBold.ttf')).arrayBuffer()));return f})();try{return await loading}catch(e){cancelMedia();throw e}finally{loading=null}}
async function run(f,args){const code=await f.exec(['-hide_banner','-y',...args]);if(code!==0)throw Error('영상 처리 실패: '+logs.slice(-4).join('\n'));}
const bytes=async b=>new Uint8Array(await b.arrayBuffer());
async function cleanup(f){try{for(const e of await f.listDir('/'))if(!e.isDir)await f.deleteFile(e.name)}catch{}}
export async function renderVideo(p,status,progress){const cuts=validCuts(p),duration=total(p);if(duration>180)throw Error('이 브라우저 버전은 한 번에 3분까지 출력합니다. 구간을 나눠 주세요.');if(!p.video)throw Error('영상 파일을 먼저 선택하세요.');const f=await ff(status);listeners.progress=progress;await cleanup(f);try{status('원본 영상을 준비하고 있어요…');await f.writeFile('source',await bytes(p.video));logs=[];await f.exec(['-hide_banner','-i','source']);const hasAudio=logs.some(x=>/Stream.*Audio:/.test(x));const w=Number(p.quality),h=w*16/9,vw=Math.round(w*.75/2)*2,vh=Math.round(h*.75/2)*2,vy=Math.round(h*440/1920/2)*2;const fitted=p.fit==='cover'?`scale=${vw}:${vh}:force_original_aspect_ratio=increase,crop=${vw}:${vh}`:`scale=${vw}:${vh}:force_original_aspect_ratio=decrease,pad=${vw}:${vh}:(ow-iw)/2:(oh-ih)/2:black`;
for(let i=0;i<cuts.length;i++){status(`영상 구간 ${i+1}/${cuts.length} 변환 중…`);const c=cuts[i],dur=c.end-c.start;const args=['-ss',String(c.start),'-i','source'];if(!hasAudio)args.push('-f','lavfi','-i','anullsrc=r=44100:cl=stereo');args.push('-t',String(dur),'-map','0:v:0','-map',hasAudio?'0:a:0':'1:a:0','-vf',`${fitted},pad=${w}:${h}:(ow-iw)/2:${vy}:black,setsar=1,fps=30`,'-af','aresample=44100','-c:v','libx264','-preset','ultrafast','-crf','23','-pix_fmt','yuv420p','-c:a','aac','-ar','44100','-ac','2',`part${i}.mp4`);await run(f,args);}
await f.writeFile('list.txt',new TextEncoder().encode(cuts.map((_,i)=>`file 'part${i}.mp4'`).join('\n')));status('구간을 이어 붙이는 중…');await run(f,['-f','concat','-safe','0','-i','list.txt','-c','copy','joined.mp4']);for(let i=0;i<cuts.length;i++)await f.deleteFile(`part${i}.mp4`);await f.deleteFile('source');await f.writeFile('captions.ass',new TextEncoder().encode(ass(p)));
const args=['-i','joined.mp4'];let idx=1,tracks=['[a0]'],filters=[`[0:a]volume=${p.originalVolume}[a0]`];if(p.narration){await f.writeFile('narration',await bytes(p.narration));args.push('-i','narration');filters.push(`[${idx++}:a]volume=${p.narrationVolume},adelay=${Math.round(p.narrationStart*1000)}:all=1,apad[a1]`);tracks.push('[a1]');}if(p.bgm){await f.writeFile('bgm',await bytes(p.bgm));args.push('-stream_loop','-1','-i','bgm');filters.push(`[${idx++}:a]volume=${p.bgmVolume}[a2]`);tracks.push('[a2]');}filters.push(`${tracks.join('')}amix=inputs=${tracks.length}:duration=first:normalize=0,alimiter=limit=0.89[a]`);args.push('-filter_complex',filters.join(';'),'-map','0:v:0','-map','[a]','-vf','ass=captions.ass:fontsdir=fonts','-t',String(duration),'-c:v','libx264','-preset','ultrafast','-crf','21','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart','final.mp4');status('제목·자막·소리를 합치는 중…');await run(f,args);const data=await f.readFile('final.mp4');return new Blob([data],{type:'video/mp4'});}finally{listeners={};await cleanup(f)}}
export async function extractAudio(p,status){if(!p.video)throw Error('영상 파일을 먼저 선택하세요.');const f=await ff(status);await cleanup(f);try{status('자막 인식을 위한 음성 추출 중…');await f.writeFile('source',await bytes(p.video));await run(f,['-i','source','-vn','-ac','1','-ar','16000','-f','f32le','audio.raw']);const a=await f.readFile('audio.raw');return new Float32Array(a.buffer.slice(a.byteOffset,a.byteOffset+a.byteLength));}finally{await cleanup(f)}}
